//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("intiModel", "fk_Obj_Empresas", "empresas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TableroComando.empresas), "objetivos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TableroComando.objetivos), true)]
[assembly: EdmRelationshipAttribute("intiModel", "fk_usuarios_empresa", "empresas", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TableroComando.empresas), "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TableroComando.usuarios), true)]
[assembly: EdmRelationshipAttribute("intiModel", "fk_Obj_Obj_destino", "objetivos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TableroComando.objetivos), "flechasobjetivos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TableroComando.flechasobjetivos), true)]
[assembly: EdmRelationshipAttribute("intiModel", "fk_Obj_Obj_origen", "objetivos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TableroComando.objetivos), "flechasobjetivos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TableroComando.flechasobjetivos), true)]
[assembly: EdmRelationshipAttribute("intiModel", "fk_Obj_tipoObj", "tipoobjetivo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TableroComando.tipoobjetivo), "objetivos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TableroComando.objetivos), true)]

#endregion

namespace TableroComando
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class intiEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new intiEntities object using the connection string found in the 'intiEntities' section of the application configuration file.
        /// </summary>
        public intiEntities() : base("name=intiEntities", "intiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new intiEntities object.
        /// </summary>
        public intiEntities(string connectionString) : base(connectionString, "intiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new intiEntities object.
        /// </summary>
        public intiEntities(EntityConnection connection) : base(connection, "intiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<empresas> empresas
        {
            get
            {
                if ((_empresas == null))
                {
                    _empresas = base.CreateObjectSet<empresas>("empresas");
                }
                return _empresas;
            }
        }
        private ObjectSet<empresas> _empresas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<flechasobjetivos> flechasobjetivos
        {
            get
            {
                if ((_flechasobjetivos == null))
                {
                    _flechasobjetivos = base.CreateObjectSet<flechasobjetivos>("flechasobjetivos");
                }
                return _flechasobjetivos;
            }
        }
        private ObjectSet<flechasobjetivos> _flechasobjetivos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<objetivos> objetivos
        {
            get
            {
                if ((_objetivos == null))
                {
                    _objetivos = base.CreateObjectSet<objetivos>("objetivos");
                }
                return _objetivos;
            }
        }
        private ObjectSet<objetivos> _objetivos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tipoobjetivo> tipoobjetivo
        {
            get
            {
                if ((_tipoobjetivo == null))
                {
                    _tipoobjetivo = base.CreateObjectSet<tipoobjetivo>("tipoobjetivo");
                }
                return _tipoobjetivo;
            }
        }
        private ObjectSet<tipoobjetivo> _tipoobjetivo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the empresas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToempresas(empresas empresas)
        {
            base.AddObject("empresas", empresas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the flechasobjetivos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToflechasobjetivos(flechasobjetivos flechasobjetivos)
        {
            base.AddObject("flechasobjetivos", flechasobjetivos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the objetivos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToobjetivos(objetivos objetivos)
        {
            base.AddObject("objetivos", objetivos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tipoobjetivo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotipoobjetivo(tipoobjetivo tipoobjetivo)
        {
            base.AddObject("tipoobjetivo", tipoobjetivo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="intiModel", Name="empresas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class empresas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new empresas object.
        /// </summary>
        /// <param name="idempresa">Initial value of the idempresa property.</param>
        /// <param name="nombreEmpresa">Initial value of the nombreEmpresa property.</param>
        /// <param name="cuit">Initial value of the cuit property.</param>
        public static empresas Createempresas(global::System.Int32 idempresa, global::System.String nombreEmpresa, global::System.String cuit)
        {
            empresas empresas = new empresas();
            empresas.idempresa = idempresa;
            empresas.nombreEmpresa = nombreEmpresa;
            empresas.cuit = cuit;
            return empresas;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idempresa
        {
            get
            {
                return _idempresa;
            }
            set
            {
                if (_idempresa != value)
                {
                    OnidempresaChanging(value);
                    ReportPropertyChanging("idempresa");
                    _idempresa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idempresa");
                    OnidempresaChanged();
                }
            }
        }
        private global::System.Int32 _idempresa;
        partial void OnidempresaChanging(global::System.Int32 value);
        partial void OnidempresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreEmpresa
        {
            get
            {
                return _nombreEmpresa;
            }
            set
            {
                OnnombreEmpresaChanging(value);
                ReportPropertyChanging("nombreEmpresa");
                _nombreEmpresa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreEmpresa");
                OnnombreEmpresaChanged();
            }
        }
        private global::System.String _nombreEmpresa;
        partial void OnnombreEmpresaChanging(global::System.String value);
        partial void OnnombreEmpresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cuit
        {
            get
            {
                return _cuit;
            }
            set
            {
                OncuitChanging(value);
                ReportPropertyChanging("cuit");
                _cuit = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cuit");
                OncuitChanged();
            }
        }
        private global::System.String _cuit;
        partial void OncuitChanging(global::System.String value);
        partial void OncuitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mision
        {
            get
            {
                return _mision;
            }
            set
            {
                OnmisionChanging(value);
                ReportPropertyChanging("mision");
                _mision = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mision");
                OnmisionChanged();
            }
        }
        private global::System.String _mision;
        partial void OnmisionChanging(global::System.String value);
        partial void OnmisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vision
        {
            get
            {
                return _vision;
            }
            set
            {
                OnvisionChanging(value);
                ReportPropertyChanging("vision");
                _vision = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vision");
                OnvisionChanged();
            }
        }
        private global::System.String _vision;
        partial void OnvisionChanging(global::System.String value);
        partial void OnvisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String valores
        {
            get
            {
                return _valores;
            }
            set
            {
                OnvaloresChanging(value);
                ReportPropertyChanging("valores");
                _valores = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("valores");
                OnvaloresChanged();
            }
        }
        private global::System.String _valores;
        partial void OnvaloresChanging(global::System.String value);
        partial void OnvaloresChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("intiModel", "fk_Obj_Empresas", "objetivos")]
        public EntityCollection<objetivos> objetivos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<objetivos>("intiModel.fk_Obj_Empresas", "objetivos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<objetivos>("intiModel.fk_Obj_Empresas", "objetivos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("intiModel", "fk_usuarios_empresa", "usuarios")]
        public EntityCollection<usuarios> usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuarios>("intiModel.fk_usuarios_empresa", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuarios>("intiModel.fk_usuarios_empresa", "usuarios", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="intiModel", Name="flechasobjetivos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class flechasobjetivos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new flechasobjetivos object.
        /// </summary>
        /// <param name="idFlecha">Initial value of the idFlecha property.</param>
        /// <param name="objOrigen">Initial value of the objOrigen property.</param>
        /// <param name="objDestino">Initial value of the objDestino property.</param>
        public static flechasobjetivos Createflechasobjetivos(global::System.Int32 idFlecha, global::System.Int32 objOrigen, global::System.Int32 objDestino)
        {
            flechasobjetivos flechasobjetivos = new flechasobjetivos();
            flechasobjetivos.idFlecha = idFlecha;
            flechasobjetivos.objOrigen = objOrigen;
            flechasobjetivos.objDestino = objDestino;
            return flechasobjetivos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idFlecha
        {
            get
            {
                return _idFlecha;
            }
            set
            {
                if (_idFlecha != value)
                {
                    OnidFlechaChanging(value);
                    ReportPropertyChanging("idFlecha");
                    _idFlecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idFlecha");
                    OnidFlechaChanged();
                }
            }
        }
        private global::System.Int32 _idFlecha;
        partial void OnidFlechaChanging(global::System.Int32 value);
        partial void OnidFlechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 objOrigen
        {
            get
            {
                return _objOrigen;
            }
            set
            {
                OnobjOrigenChanging(value);
                ReportPropertyChanging("objOrigen");
                _objOrigen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("objOrigen");
                OnobjOrigenChanged();
            }
        }
        private global::System.Int32 _objOrigen;
        partial void OnobjOrigenChanging(global::System.Int32 value);
        partial void OnobjOrigenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 objDestino
        {
            get
            {
                return _objDestino;
            }
            set
            {
                OnobjDestinoChanging(value);
                ReportPropertyChanging("objDestino");
                _objDestino = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("objDestino");
                OnobjDestinoChanged();
            }
        }
        private global::System.Int32 _objDestino;
        partial void OnobjDestinoChanging(global::System.Int32 value);
        partial void OnobjDestinoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("intiModel", "fk_Obj_Obj_destino", "objetivos")]
        public objetivos objetivos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<objetivos>("intiModel.fk_Obj_Obj_destino", "objetivos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<objetivos>("intiModel.fk_Obj_Obj_destino", "objetivos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<objetivos> objetivosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<objetivos>("intiModel.fk_Obj_Obj_destino", "objetivos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<objetivos>("intiModel.fk_Obj_Obj_destino", "objetivos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("intiModel", "fk_Obj_Obj_origen", "objetivos")]
        public objetivos objetivos1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<objetivos>("intiModel.fk_Obj_Obj_origen", "objetivos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<objetivos>("intiModel.fk_Obj_Obj_origen", "objetivos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<objetivos> objetivos1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<objetivos>("intiModel.fk_Obj_Obj_origen", "objetivos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<objetivos>("intiModel.fk_Obj_Obj_origen", "objetivos", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="intiModel", Name="objetivos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class objetivos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new objetivos object.
        /// </summary>
        /// <param name="idobjetivo">Initial value of the idobjetivo property.</param>
        /// <param name="empresa">Initial value of the empresa property.</param>
        /// <param name="tipoObj">Initial value of the tipoObj property.</param>
        /// <param name="titulo">Initial value of the titulo property.</param>
        public static objetivos Createobjetivos(global::System.Int32 idobjetivo, global::System.Int32 empresa, global::System.Int32 tipoObj, global::System.String titulo)
        {
            objetivos objetivos = new objetivos();
            objetivos.idobjetivo = idobjetivo;
            objetivos.empresa = empresa;
            objetivos.tipoObj = tipoObj;
            objetivos.titulo = titulo;
            return objetivos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idobjetivo
        {
            get
            {
                return _idobjetivo;
            }
            set
            {
                if (_idobjetivo != value)
                {
                    OnidobjetivoChanging(value);
                    ReportPropertyChanging("idobjetivo");
                    _idobjetivo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idobjetivo");
                    OnidobjetivoChanged();
                }
            }
        }
        private global::System.Int32 _idobjetivo;
        partial void OnidobjetivoChanging(global::System.Int32 value);
        partial void OnidobjetivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 empresa
        {
            get
            {
                return _empresa;
            }
            set
            {
                OnempresaChanging(value);
                ReportPropertyChanging("empresa");
                _empresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("empresa");
                OnempresaChanged();
            }
        }
        private global::System.Int32 _empresa;
        partial void OnempresaChanging(global::System.Int32 value);
        partial void OnempresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipoObj
        {
            get
            {
                return _tipoObj;
            }
            set
            {
                OntipoObjChanging(value);
                ReportPropertyChanging("tipoObj");
                _tipoObj = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipoObj");
                OntipoObjChanged();
            }
        }
        private global::System.Int32 _tipoObj;
        partial void OntipoObjChanging(global::System.Int32 value);
        partial void OntipoObjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private global::System.String _titulo;
        partial void OntituloChanging(global::System.String value);
        partial void OntituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.String _numero;
        partial void OnnumeroChanging(global::System.String value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("intiModel", "fk_Obj_Empresas", "empresas")]
        public empresas empresas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresas>("intiModel.fk_Obj_Empresas", "empresas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresas>("intiModel.fk_Obj_Empresas", "empresas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<empresas> empresasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresas>("intiModel.fk_Obj_Empresas", "empresas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<empresas>("intiModel.fk_Obj_Empresas", "empresas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("intiModel", "fk_Obj_Obj_destino", "flechasobjetivos")]
        public EntityCollection<flechasobjetivos> flechasobjetivos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<flechasobjetivos>("intiModel.fk_Obj_Obj_destino", "flechasobjetivos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<flechasobjetivos>("intiModel.fk_Obj_Obj_destino", "flechasobjetivos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("intiModel", "fk_Obj_Obj_origen", "flechasobjetivos")]
        public EntityCollection<flechasobjetivos> flechasobjetivos1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<flechasobjetivos>("intiModel.fk_Obj_Obj_origen", "flechasobjetivos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<flechasobjetivos>("intiModel.fk_Obj_Obj_origen", "flechasobjetivos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("intiModel", "fk_Obj_tipoObj", "tipoobjetivo")]
        public tipoobjetivo tipoobjetivo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipoobjetivo>("intiModel.fk_Obj_tipoObj", "tipoobjetivo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipoobjetivo>("intiModel.fk_Obj_tipoObj", "tipoobjetivo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tipoobjetivo> tipoobjetivoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipoobjetivo>("intiModel.fk_Obj_tipoObj", "tipoobjetivo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tipoobjetivo>("intiModel.fk_Obj_tipoObj", "tipoobjetivo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="intiModel", Name="tipoobjetivo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tipoobjetivo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tipoobjetivo object.
        /// </summary>
        /// <param name="idTipoObjetivo">Initial value of the idTipoObjetivo property.</param>
        /// <param name="nombreTipoObjetivo">Initial value of the nombreTipoObjetivo property.</param>
        public static tipoobjetivo Createtipoobjetivo(global::System.Int32 idTipoObjetivo, global::System.String nombreTipoObjetivo)
        {
            tipoobjetivo tipoobjetivo = new tipoobjetivo();
            tipoobjetivo.idTipoObjetivo = idTipoObjetivo;
            tipoobjetivo.nombreTipoObjetivo = nombreTipoObjetivo;
            return tipoobjetivo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTipoObjetivo
        {
            get
            {
                return _idTipoObjetivo;
            }
            set
            {
                if (_idTipoObjetivo != value)
                {
                    OnidTipoObjetivoChanging(value);
                    ReportPropertyChanging("idTipoObjetivo");
                    _idTipoObjetivo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTipoObjetivo");
                    OnidTipoObjetivoChanged();
                }
            }
        }
        private global::System.Int32 _idTipoObjetivo;
        partial void OnidTipoObjetivoChanging(global::System.Int32 value);
        partial void OnidTipoObjetivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreTipoObjetivo
        {
            get
            {
                return _nombreTipoObjetivo;
            }
            set
            {
                OnnombreTipoObjetivoChanging(value);
                ReportPropertyChanging("nombreTipoObjetivo");
                _nombreTipoObjetivo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreTipoObjetivo");
                OnnombreTipoObjetivoChanged();
            }
        }
        private global::System.String _nombreTipoObjetivo;
        partial void OnnombreTipoObjetivoChanging(global::System.String value);
        partial void OnnombreTipoObjetivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("intiModel", "fk_Obj_tipoObj", "objetivos")]
        public EntityCollection<objetivos> objetivos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<objetivos>("intiModel.fk_Obj_tipoObj", "objetivos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<objetivos>("intiModel.fk_Obj_tipoObj", "objetivos", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="intiModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuarios object.
        /// </summary>
        /// <param name="idusuario">Initial value of the idusuario property.</param>
        public static usuarios Createusuarios(global::System.Int32 idusuario)
        {
            usuarios usuarios = new usuarios();
            usuarios.idusuario = idusuario;
            return usuarios;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                if (_idusuario != value)
                {
                    OnidusuarioChanging(value);
                    ReportPropertyChanging("idusuario");
                    _idusuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idusuario");
                    OnidusuarioChanged();
                }
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pass
        {
            get
            {
                return _pass;
            }
            set
            {
                OnpassChanging(value);
                ReportPropertyChanging("pass");
                _pass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pass");
                OnpassChanged();
            }
        }
        private global::System.String _pass;
        partial void OnpassChanging(global::System.String value);
        partial void OnpassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombrereal
        {
            get
            {
                return _nombrereal;
            }
            set
            {
                OnnombrerealChanging(value);
                ReportPropertyChanging("nombrereal");
                _nombrereal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombrereal");
                OnnombrerealChanged();
            }
        }
        private global::System.String _nombrereal;
        partial void OnnombrerealChanging(global::System.String value);
        partial void OnnombrerealChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> empresa
        {
            get
            {
                return _empresa;
            }
            set
            {
                OnempresaChanging(value);
                ReportPropertyChanging("empresa");
                _empresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("empresa");
                OnempresaChanged();
            }
        }
        private Nullable<global::System.Int32> _empresa;
        partial void OnempresaChanging(Nullable<global::System.Int32> value);
        partial void OnempresaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("intiModel", "fk_usuarios_empresa", "empresas")]
        public empresas empresas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresas>("intiModel.fk_usuarios_empresa", "empresas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresas>("intiModel.fk_usuarios_empresa", "empresas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<empresas> empresasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresas>("intiModel.fk_usuarios_empresa", "empresas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<empresas>("intiModel.fk_usuarios_empresa", "empresas", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
